"""
Generate seed_social.sql — a single SQL file you can paste into the
Supabase SQL editor to set up all social media tables from scratch.

Outputs:  pipeline/data/seed_social.sql

Contents:
  1. CREATE SCHEMA IF NOT EXISTS operational + warehouse
  2. CREATE TABLE operational.social_media_posts  +  812 INSERT rows
  3. CREATE TABLE warehouse.fact_social_media_ml  (encoded features + targets)
  4. CREATE TABLE operational.social_media_predictions  (empty, for inference)
"""

import math
from pathlib import Path

import pandas as pd

DATA_DIR = Path(__file__).resolve().parents[1] / "data"
OUT_PATH  = DATA_DIR / "seed_social.sql"
CSV_PATH  = DATA_DIR / "social_media_posts.csv"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _sql_val(v) -> str:
    """Convert a Python value to a SQL literal."""
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return repr(v)
    # String — escape single quotes
    return "'" + str(v).replace("'", "''") + "'"


def _insert_block(df: pd.DataFrame, schema: str, table: str, chunk: int = 100) -> str:
    cols = ", ".join(df.columns)
    lines = []
    rows = list(df.itertuples(index=False, name=None))
    for i in range(0, len(rows), chunk):
        batch = rows[i : i + chunk]
        vals = ",\n    ".join(
            "(" + ", ".join(_sql_val(v) for v in row) + ")"
            for row in batch
        )
        lines.append(f"INSERT INTO {schema}.{table} ({cols}) VALUES\n    {vals};")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Build SQL
# ---------------------------------------------------------------------------

def generate():
    df = pd.read_csv(CSV_PATH)

    # Normalise boolean columns read from CSV (may be strings "True"/"False")
    for col in ["has_call_to_action", "features_resident_story", "is_boosted"]:
        df[col] = df[col].map({"True": True, "False": False, True: True, False: False})

    lines = []

    # ------------------------------------------------------------------
    # 1. Schemas
    # ------------------------------------------------------------------
    lines += [
        "-- ================================================================",
        "-- Lighthouse Sanctuary — Social Media Seed SQL",
        "-- Generated by pipeline/jobs/generate_seed_sql.py",
        "-- Paste this entire file into the Supabase SQL editor and run.",
        "-- ================================================================",
        "",
        "CREATE SCHEMA IF NOT EXISTS operational;",
        "CREATE SCHEMA IF NOT EXISTS warehouse;",
        "",
    ]

    # ------------------------------------------------------------------
    # 2. operational.social_media_posts  (39 columns, raw data)
    # ------------------------------------------------------------------
    lines += [
        "-- ================================================================",
        "-- 2. operational.social_media_posts",
        "-- ================================================================",
        "DROP TABLE IF EXISTS operational.social_media_posts CASCADE;",
        "CREATE TABLE operational.social_media_posts (",
        "    post_id                       INTEGER PRIMARY KEY,",
        "    platform                      TEXT,",
        "    platform_post_id              TEXT,",
        "    post_url                      TEXT,",
        "    created_at                    TIMESTAMPTZ,",
        "    day_of_week                   TEXT,",
        "    post_hour                     INTEGER,",
        "    post_type                     TEXT,",
        "    media_type                    TEXT,",
        "    caption                       TEXT,",
        "    hashtags                      TEXT,",
        "    num_hashtags                  INTEGER,",
        "    mentions_count                INTEGER,",
        "    has_call_to_action            BOOLEAN,",
        "    call_to_action_type           TEXT,",
        "    content_topic                 TEXT,",
        "    sentiment_tone                TEXT,",
        "    caption_length                INTEGER,",
        "    features_resident_story       BOOLEAN,",
        "    campaign_name                 TEXT,",
        "    is_boosted                    BOOLEAN,",
        "    boost_budget_php              DOUBLE PRECISION,",
        "    impressions                   INTEGER,",
        "    reach                         INTEGER,",
        "    likes                         INTEGER,",
        "    comments                      INTEGER,",
        "    shares                        INTEGER,",
        "    saves                         INTEGER,",
        "    click_throughs                INTEGER,",
        "    video_views                   DOUBLE PRECISION,",
        "    engagement_rate               DOUBLE PRECISION,",
        "    profile_visits                INTEGER,",
        "    donation_referrals            INTEGER,",
        "    estimated_donation_value_php  DOUBLE PRECISION,",
        "    follower_count_at_post        INTEGER,",
        "    watch_time_seconds            DOUBLE PRECISION,",
        "    avg_view_duration_seconds     DOUBLE PRECISION,",
        "    subscriber_count_at_post      DOUBLE PRECISION,",
        "    forwards                      DOUBLE PRECISION",
        ");",
        "",
    ]

    # Cast created_at to string so _sql_val wraps it as a quoted literal
    insert_df = df.copy()
    insert_df["created_at"] = insert_df["created_at"].astype(str)
    # Replace NaN in object columns with None
    insert_df = insert_df.where(pd.notnull(insert_df), None)

    lines.append(_insert_block(insert_df, "operational", "social_media_posts"))
    lines.append("")

    # ------------------------------------------------------------------
    # 3. warehouse.fact_social_media_ml  (encoded features + targets)
    # ------------------------------------------------------------------
    lines += [
        "-- ================================================================",
        "-- 3. warehouse.fact_social_media_ml",
        "-- ================================================================",
        "DROP TABLE IF EXISTS warehouse.fact_social_media_ml CASCADE;",
        "CREATE TABLE warehouse.fact_social_media_ml AS",
        "SELECT",
        "    post_id,",
        "    -- Categorical encodings",
        "    CASE platform",
        "        WHEN 'Facebook'  THEN 0 WHEN 'Instagram' THEN 1 WHEN 'LinkedIn' THEN 2",
        "        WHEN 'TikTok'    THEN 3 WHEN 'Twitter'   THEN 4 WHEN 'WhatsApp' THEN 5",
        "        WHEN 'YouTube'   THEN 6 ELSE -1 END                          AS platform_encoded,",
        "    CASE post_type",
        "        WHEN 'Campaign'           THEN 0 WHEN 'EducationalContent' THEN 1",
        "        WHEN 'EventPromotion'     THEN 2 WHEN 'FundraisingAppeal'  THEN 3",
        "        WHEN 'ImpactStory'        THEN 4 WHEN 'ThankYou'           THEN 5",
        "        ELSE -1 END                                                   AS post_type_encoded,",
        "    CASE media_type",
        "        WHEN 'Carousel' THEN 0 WHEN 'Photo' THEN 1 WHEN 'Reel' THEN 2",
        "        WHEN 'Text'     THEN 3 WHEN 'Video' THEN 4 ELSE -1 END       AS media_type_encoded,",
        "    CASE day_of_week",
        "        WHEN 'Friday'    THEN 0 WHEN 'Monday'   THEN 1 WHEN 'Saturday' THEN 2",
        "        WHEN 'Sunday'    THEN 3 WHEN 'Thursday' THEN 4 WHEN 'Tuesday'  THEN 5",
        "        WHEN 'Wednesday' THEN 6 ELSE -1 END                          AS day_of_week_encoded,",
        "    CASE COALESCE(call_to_action_type, 'None')",
        "        WHEN 'DonateNow'  THEN 0 WHEN 'LearnMore' THEN 1 WHEN 'None'       THEN 2",
        "        WHEN 'ShareStory' THEN 3 WHEN 'SignUp'    THEN 4 ELSE -1 END AS call_to_action_type_encoded,",
        "    CASE content_topic",
        "        WHEN 'AwarenessRaising' THEN 0 WHEN 'CampaignLaunch' THEN 1 WHEN 'DonorImpact'  THEN 2",
        "        WHEN 'Education'        THEN 3 WHEN 'EventRecap'     THEN 4 WHEN 'Gratitude'     THEN 5",
        "        WHEN 'Health'           THEN 6 WHEN 'Reintegration'  THEN 7 WHEN 'SafehouseLife' THEN 8",
        "        ELSE -1 END                                                   AS content_topic_encoded,",
        "    CASE sentiment_tone",
        "        WHEN 'Celebratory' THEN 0 WHEN 'Emotional'   THEN 1 WHEN 'Grateful'    THEN 2",
        "        WHEN 'Hopeful'     THEN 3 WHEN 'Informative' THEN 4 WHEN 'Urgent'       THEN 5",
        "        ELSE -1 END                                                   AS sentiment_tone_encoded,",
        "    -- Boolean features",
        "    CASE WHEN has_call_to_action      THEN 1 ELSE 0 END              AS has_call_to_action,",
        "    CASE WHEN features_resident_story THEN 1 ELSE 0 END              AS features_resident_story,",
        "    CASE WHEN is_boosted              THEN 1 ELSE 0 END              AS is_boosted,",
        "    -- Numeric features",
        "    post_hour,",
        "    num_hashtags,",
        "    mentions_count,",
        "    caption_length,",
        "    COALESCE(boost_budget_php, 0.0)                                  AS boost_budget_php,",
        "    follower_count_at_post,",
        "    -- Target labels",
        "    CASE",
        "        WHEN NTILE(3) OVER (ORDER BY engagement_rate) = 1 THEN 'Low'",
        "        WHEN NTILE(3) OVER (ORDER BY engagement_rate) = 2 THEN 'Medium'",
        "        ELSE 'High'",
        "    END                                                               AS engagement_tier,",
        "    CASE WHEN donation_referrals > 0 THEN 1 ELSE 0 END              AS has_donations",
        "FROM operational.social_media_posts;",
        "",
        "ALTER TABLE warehouse.fact_social_media_ml",
        "    ADD PRIMARY KEY (post_id);",
        "",
    ]

    # ------------------------------------------------------------------
    # 4. operational.social_media_predictions  (empty — filled by inference)
    # ------------------------------------------------------------------
    lines += [
        "-- ================================================================",
        "-- 4. operational.social_media_predictions  (filled by inference_social.py)",
        "-- ================================================================",
        "CREATE TABLE IF NOT EXISTS operational.social_media_predictions (",
        "    post_id                    INTEGER          PRIMARY KEY,",
        "    predicted_engagement_tier  TEXT,",
        "    prob_engagement_low        DOUBLE PRECISION,",
        "    prob_engagement_medium     DOUBLE PRECISION,",
        "    prob_engagement_high       DOUBLE PRECISION,",
        "    predicted_has_donations    INTEGER,",
        "    prob_has_donations         DOUBLE PRECISION,",
        "    prediction_ts              TIMESTAMPTZ",
        ");",
        "",
        "-- Done! Next steps:",
        "--   1. Add pipeline/.env with your Supabase credentials",
        "--   2. cd pipeline/jobs && python train_social.py",
        "--   3. python inference_social.py",
    ]

    sql = "\n".join(lines)
    OUT_PATH.write_text(sql, encoding="utf-8")
    print(f"Written: {OUT_PATH}")
    print(f"  social_media_posts rows: {len(df)}")
    print(f"  File size: {OUT_PATH.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    generate()
