// <auto-generated />
using System;
using INTEX_II.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace INTEX_II.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406230946_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("INTEX_II.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("donation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DonationId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("CampaignName")
                        .HasColumnType("text")
                        .HasColumnName("campaign_name");

                    b.Property<string>("ChannelSource")
                        .HasColumnType("text")
                        .HasColumnName("channel_source");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly?>("DonationDate")
                        .HasColumnType("date")
                        .HasColumnName("donation_date");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("donation_type");

                    b.Property<decimal>("EstimatedValue")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_value");

                    b.Property<string>("ImpactUnit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("impact_unit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("integer")
                        .HasColumnName("referral_post_id");

                    b.Property<int>("SupporterId")
                        .HasColumnType("integer")
                        .HasColumnName("supporter_id");

                    b.HasKey("DonationId")
                        .HasName("pk_donations");

                    b.HasIndex("ReferralPostId")
                        .HasDatabaseName("ix_donations_referral_post_id");

                    b.HasIndex("SupporterId")
                        .HasDatabaseName("ix_donations_supporter_id");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("allocation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllocationId"));

                    b.Property<DateOnly>("AllocationDate")
                        .HasColumnType("date")
                        .HasColumnName("allocation_date");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("text")
                        .HasColumnName("allocation_notes");

                    b.Property<decimal>("AmountAllocated")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_allocated");

                    b.Property<int>("DonationId")
                        .HasColumnType("integer")
                        .HasColumnName("donation_id");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_area");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.HasKey("AllocationId")
                        .HasName("pk_donation_allocations");

                    b.HasIndex("DonationId")
                        .HasDatabaseName("ix_donation_allocations_donation_id");

                    b.HasIndex("SafehouseId")
                        .HasDatabaseName("ix_donation_allocations_safehouse_id");

                    b.ToTable("donation_allocations", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("education_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EducationRecordId"));

                    b.Property<decimal>("AttendanceRate")
                        .HasColumnType("numeric")
                        .HasColumnName("attendance_rate");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("completion_status");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("education_level");

                    b.Property<string>("EnrollmentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enrollment_status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("ProgressPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("progress_percent");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("school_name");

                    b.HasKey("EducationRecordId")
                        .HasName("pk_education_records");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_education_records_resident_id");

                    b.ToTable("education_records", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("health_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HealthRecordId"));

                    b.Property<decimal>("Bmi")
                        .HasColumnType("numeric")
                        .HasColumnName("bmi");

                    b.Property<bool>("DentalCheckupDone")
                        .HasColumnType("boolean")
                        .HasColumnName("dental_checkup_done");

                    b.Property<decimal>("EnergyLevelScore")
                        .HasColumnType("numeric")
                        .HasColumnName("energy_level_score");

                    b.Property<decimal>("GeneralHealthScore")
                        .HasColumnType("numeric")
                        .HasColumnName("general_health_score");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("numeric")
                        .HasColumnName("height_cm");

                    b.Property<bool>("MedicalCheckupDone")
                        .HasColumnType("boolean")
                        .HasColumnName("medical_checkup_done");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("NutritionScore")
                        .HasColumnType("numeric")
                        .HasColumnName("nutrition_score");

                    b.Property<bool>("PsychologicalCheckupDone")
                        .HasColumnType("boolean")
                        .HasColumnName("psychological_checkup_done");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<decimal>("SleepQualityScore")
                        .HasColumnType("numeric")
                        .HasColumnName("sleep_quality_score");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_kg");

                    b.HasKey("HealthRecordId")
                        .HasName("pk_health_wellbeing_records");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_health_wellbeing_records_resident_id");

                    b.ToTable("health_wellbeing_records", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("visitation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VisitationId"));

                    b.Property<string>("FamilyCooperationLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("family_cooperation_level");

                    b.Property<string>("FamilyMembersPresent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("family_members_present");

                    b.Property<bool>("FollowUpNeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("follow_up_needed");

                    b.Property<string>("FollowUpNotes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("follow_up_notes");

                    b.Property<string>("LocationVisited")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location_visited");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<bool>("SafetyConcernsNoted")
                        .HasColumnType("boolean")
                        .HasColumnName("safety_concerns_noted");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("social_worker");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.Property<string>("VisitOutcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visit_outcome");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visit_type");

                    b.HasKey("VisitationId")
                        .HasName("pk_home_visitations");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_home_visitations_resident_id");

                    b.ToTable("home_visitations", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int>("DonationId")
                        .HasColumnType("integer")
                        .HasColumnName("donation_id");

                    b.Property<decimal>("EstimatedUnitValue")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_unit_value");

                    b.Property<string>("IntendedUse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intended_use");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_category");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ReceivedCondition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("received_condition");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("ItemId")
                        .HasName("pk_in_kind_donation_items");

                    b.HasIndex("DonationId")
                        .HasDatabaseName("ix_in_kind_donation_items_donation_id");

                    b.ToTable("in_kind_donation_items", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("incident_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("FollowUpRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("follow_up_required");

                    b.Property<DateOnly>("IncidentDate")
                        .HasColumnType("date")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("incident_type");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reported_by");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("date")
                        .HasColumnName("resolution_date");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<string>("ResponseTaken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_taken");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.HasKey("IncidentId")
                        .HasName("pk_incident_reports");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_incident_reports_resident_id");

                    b.HasIndex("SafehouseId")
                        .HasDatabaseName("ix_incident_reports_safehouse_id");

                    b.ToTable("incident_reports", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<DateOnly>("CaseConferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("case_conference_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_category");

                    b.Property<string>("PlanDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_description");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<string>("ServicesProvided")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("services_provided");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("numeric")
                        .HasColumnName("target_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlanId")
                        .HasName("pk_intervention_plans");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_intervention_plans_resident_id");

                    b.ToTable("intervention_plans", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("partner_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartnerId"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partner_name");

                    b.Property<string>("PartnerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partner_type");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("PartnerId")
                        .HasName("pk_partners");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateOnly?>("AssignmentEnd")
                        .HasColumnType("date")
                        .HasColumnName("assignment_end");

                    b.Property<DateOnly>("AssignmentStart")
                        .HasColumnType("date")
                        .HasColumnName("assignment_start");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("PartnerId")
                        .HasColumnType("integer")
                        .HasColumnName("partner_id");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_area");

                    b.Property<string>("ResponsibilityNotes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsibility_notes");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("AssignmentId")
                        .HasName("pk_partner_assignments");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_partner_assignments_partner_id");

                    b.HasIndex("SafehouseId")
                        .HasDatabaseName("ix_partner_assignments_safehouse_id");

                    b.ToTable("partner_assignments", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recording_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecordingId"));

                    b.Property<bool>("ConcernsFlagged")
                        .HasColumnType("boolean")
                        .HasColumnName("concerns_flagged");

                    b.Property<string>("EmotionalStateEnd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emotional_state_end");

                    b.Property<string>("EmotionalStateObserved")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emotional_state_observed");

                    b.Property<string>("FollowUpActions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("follow_up_actions");

                    b.Property<string>("InterventionsApplied")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interventions_applied");

                    b.Property<string>("NotesRestricted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes_restricted");

                    b.Property<bool>("ProgressNoted")
                        .HasColumnType("boolean")
                        .HasColumnName("progress_noted");

                    b.Property<bool>("ReferralMade")
                        .HasColumnType("boolean")
                        .HasColumnName("referral_made");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<int>("SessionDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("session_duration_minutes");

                    b.Property<string>("SessionNarrative")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_narrative");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_type");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("social_worker");

                    b.HasKey("RecordingId")
                        .HasName("pk_process_recordings");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_process_recordings_resident_id");

                    b.ToTable("process_recordings", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SnapshotId"));

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headline");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("MetricPayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_payload_json");

                    b.Property<DateOnly?>("PublishedAt")
                        .HasColumnType("date")
                        .HasColumnName("published_at");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary_text");

                    b.HasKey("SnapshotId")
                        .HasName("pk_public_impact_snapshots");

                    b.ToTable("public_impact_snapshots", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResidentId"));

                    b.Property<string>("AgeUponAdmission")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("age_upon_admission");

                    b.Property<string>("AssignedSocialWorker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assigned_social_worker");

                    b.Property<string>("BirthStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("birth_status");

                    b.Property<string>("CaseCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_category");

                    b.Property<string>("CaseControlNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_control_no");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentRiskLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_risk_level");

                    b.Property<DateOnly?>("DateCaseStudyPrepared")
                        .HasColumnType("date")
                        .HasColumnName("date_case_study_prepared");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("date")
                        .HasColumnName("date_closed");

                    b.Property<DateOnly?>("DateColbObtained")
                        .HasColumnType("date")
                        .HasColumnName("date_colb_obtained");

                    b.Property<DateOnly?>("DateColbRegistered")
                        .HasColumnType("date")
                        .HasColumnName("date_colb_registered");

                    b.Property<DateOnly?>("DateEnrolled")
                        .HasColumnType("date")
                        .HasColumnName("date_enrolled");

                    b.Property<DateOnly>("DateOfAdmission")
                        .HasColumnType("date")
                        .HasColumnName("date_of_admission");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<bool>("FamilyIndigenous")
                        .HasColumnType("boolean")
                        .HasColumnName("family_indigenous");

                    b.Property<bool>("FamilyInformalSettler")
                        .HasColumnType("boolean")
                        .HasColumnName("family_informal_settler");

                    b.Property<bool>("FamilyIs4Ps")
                        .HasColumnType("boolean")
                        .HasColumnName("family_is4ps");

                    b.Property<bool>("FamilyParentPwd")
                        .HasColumnType("boolean")
                        .HasColumnName("family_parent_pwd");

                    b.Property<bool>("FamilySoloParent")
                        .HasColumnType("boolean")
                        .HasColumnName("family_solo_parent");

                    b.Property<bool>("HasSpecialNeeds")
                        .HasColumnType("boolean")
                        .HasColumnName("has_special_needs");

                    b.Property<string>("InitialCaseAssessment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initial_case_assessment");

                    b.Property<string>("InitialRiskLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initial_risk_level");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("internal_code");

                    b.Property<bool>("IsPwd")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pwd");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("text")
                        .HasColumnName("length_of_stay");

                    b.Property<string>("NotesRestricted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes_restricted");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("PresentAge")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("present_age");

                    b.Property<string>("PwdType")
                        .HasColumnType("text")
                        .HasColumnName("pwd_type");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("text")
                        .HasColumnName("referral_source");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("text")
                        .HasColumnName("referring_agency_person");

                    b.Property<string>("ReintegrationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reintegration_status");

                    b.Property<string>("ReintegrationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reintegration_type");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("religion");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("special_needs_diagnosis");

                    b.Property<bool>("SubCatAtRisk")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_at_risk");

                    b.Property<bool>("SubCatChildLabor")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_child_labor");

                    b.Property<bool>("SubCatChildWithHiv")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_child_with_hiv");

                    b.Property<bool>("SubCatCicl")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_cicl");

                    b.Property<bool>("SubCatOrphaned")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_orphaned");

                    b.Property<bool>("SubCatOsaec")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_osaec");

                    b.Property<bool>("SubCatPhysicalAbuse")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_physical_abuse");

                    b.Property<bool>("SubCatSexualAbuse")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_sexual_abuse");

                    b.Property<bool>("SubCatStreetChild")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_street_child");

                    b.Property<bool>("SubCatTrafficked")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_trafficked");

                    b.HasKey("ResidentId")
                        .HasName("pk_residents");

                    b.HasIndex("SafehouseId")
                        .HasDatabaseName("ix_residents_safehouse_id");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SafehouseId"));

                    b.Property<int>("CapacityGirls")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_girls");

                    b.Property<int>("CapacityStaff")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_staff");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("integer")
                        .HasColumnName("current_occupancy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("OpenDate")
                        .HasColumnType("date")
                        .HasColumnName("open_date");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("SafehouseCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("safehouse_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("SafehouseId")
                        .HasName("pk_safehouses");

                    b.ToTable("safehouses", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("metric_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetricId"));

                    b.Property<int>("ActiveResidents")
                        .HasColumnType("integer")
                        .HasColumnName("active_residents");

                    b.Property<decimal>("AvgEducationProgress")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_education_progress");

                    b.Property<decimal>("AvgHealthScore")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_health_score");

                    b.Property<int>("HomeVisitationCount")
                        .HasColumnType("integer")
                        .HasColumnName("home_visitation_count");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("integer")
                        .HasColumnName("incident_count");

                    b.Property<DateOnly?>("MonthEnd")
                        .HasColumnType("date")
                        .HasColumnName("month_end");

                    b.Property<DateOnly>("MonthStart")
                        .HasColumnType("date")
                        .HasColumnName("month_start");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProcessRecordingCount")
                        .HasColumnType("integer")
                        .HasColumnName("process_recording_count");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("safehouse_id");

                    b.HasKey("MetricId")
                        .HasName("pk_safehouse_monthly_metrics");

                    b.HasIndex("SafehouseId")
                        .HasDatabaseName("ix_safehouse_monthly_metrics_safehouse_id");

                    b.ToTable("safehouse_monthly_metrics", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<decimal?>("AvgViewDurationSeconds")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_view_duration_seconds");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasColumnType("numeric")
                        .HasColumnName("boost_budget_php");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("text")
                        .HasColumnName("call_to_action_type");

                    b.Property<string>("CampaignName")
                        .HasColumnType("text")
                        .HasColumnName("campaign_name");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<int?>("CaptionLength")
                        .HasColumnType("integer")
                        .HasColumnName("caption_length");

                    b.Property<int>("ClickThroughs")
                        .HasColumnType("integer")
                        .HasColumnName("click_throughs");

                    b.Property<int>("Comments")
                        .HasColumnType("integer")
                        .HasColumnName("comments");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("text")
                        .HasColumnName("content_topic");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<int>("DonationReferrals")
                        .HasColumnType("integer")
                        .HasColumnName("donation_referrals");

                    b.Property<decimal>("EngagementRate")
                        .HasColumnType("numeric")
                        .HasColumnName("engagement_rate");

                    b.Property<decimal>("EstimatedDonationValuePhp")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_donation_value_php");

                    b.Property<bool>("FeaturesResidentStory")
                        .HasColumnType("boolean")
                        .HasColumnName("features_resident_story");

                    b.Property<int>("FollowerCountAtPost")
                        .HasColumnType("integer")
                        .HasColumnName("follower_count_at_post");

                    b.Property<decimal?>("Forwards")
                        .HasColumnType("numeric")
                        .HasColumnName("forwards");

                    b.Property<bool>("HasCallToAction")
                        .HasColumnType("boolean")
                        .HasColumnName("has_call_to_action");

                    b.Property<string>("Hashtags")
                        .HasColumnType("text")
                        .HasColumnName("hashtags");

                    b.Property<int>("Impressions")
                        .HasColumnType("integer")
                        .HasColumnName("impressions");

                    b.Property<bool>("IsBoosted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_boosted");

                    b.Property<int>("Likes")
                        .HasColumnType("integer")
                        .HasColumnName("likes");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<int?>("MentionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("mentions_count");

                    b.Property<int?>("NumHashtags")
                        .HasColumnType("integer")
                        .HasColumnName("num_hashtags");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformPostId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform_post_id");

                    b.Property<int>("PostHour")
                        .HasColumnType("integer")
                        .HasColumnName("post_hour");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_type");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_url");

                    b.Property<int>("ProfileVisits")
                        .HasColumnType("integer")
                        .HasColumnName("profile_visits");

                    b.Property<int>("Reach")
                        .HasColumnType("integer")
                        .HasColumnName("reach");

                    b.Property<int>("Saves")
                        .HasColumnType("integer")
                        .HasColumnName("saves");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("text")
                        .HasColumnName("sentiment_tone");

                    b.Property<int>("Shares")
                        .HasColumnType("integer")
                        .HasColumnName("shares");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("integer")
                        .HasColumnName("subscriber_count_at_post");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("integer")
                        .HasColumnName("video_views");

                    b.Property<decimal?>("WatchTimeSeconds")
                        .HasColumnType("numeric")
                        .HasColumnName("watch_time_seconds");

                    b.HasKey("PostId")
                        .HasName("pk_social_media_posts");

                    b.ToTable("social_media_posts", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("supporter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupporterId"));

                    b.Property<string>("AcquisitionChannel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acquisition_channel");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("FirstDonationDate")
                        .HasColumnType("date")
                        .HasColumnName("first_donation_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relationship_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SupporterType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supporter_type");

                    b.HasKey("SupporterId")
                        .HasName("pk_supporters");

                    b.ToTable("supporters", (string)null);
                });

            modelBuilder.Entity("INTEX_II.Models.Donation", b =>
                {
                    b.HasOne("INTEX_II.Models.SocialMediaPost", "ReferralPost")
                        .WithMany("ReferralDonations")
                        .HasForeignKey("ReferralPostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_donations_social_media_posts_referral_post_id");

                    b.HasOne("INTEX_II.Models.Supporter", "Supporter")
                        .WithMany("Donations")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_donations_supporters_supporter_id");

                    b.Navigation("ReferralPost");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("INTEX_II.Models.DonationAllocation", b =>
                {
                    b.HasOne("INTEX_II.Models.Donation", "Donation")
                        .WithMany("Allocations")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_donation_allocations_donations_donation_id");

                    b.HasOne("INTEX_II.Models.Safehouse", "Safehouse")
                        .WithMany("DonationAllocations")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_donation_allocations_safehouses_safehouse_id");

                    b.Navigation("Donation");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("INTEX_II.Models.EducationRecord", b =>
                {
                    b.HasOne("INTEX_II.Models.Resident", "Resident")
                        .WithMany("EducationRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_education_records_residents_resident_id");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("INTEX_II.Models.HealthWellbeingRecord", b =>
                {
                    b.HasOne("INTEX_II.Models.Resident", "Resident")
                        .WithMany("HealthRecords")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_wellbeing_records_residents_resident_id");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("INTEX_II.Models.HomeVisitation", b =>
                {
                    b.HasOne("INTEX_II.Models.Resident", "Resident")
                        .WithMany("HomeVisitations")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_home_visitations_residents_resident_id");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("INTEX_II.Models.InKindDonationItem", b =>
                {
                    b.HasOne("INTEX_II.Models.Donation", "Donation")
                        .WithMany("InKindItems")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_in_kind_donation_items_donations_donation_id");

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("INTEX_II.Models.IncidentReport", b =>
                {
                    b.HasOne("INTEX_II.Models.Resident", "Resident")
                        .WithMany("IncidentReports")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incident_reports_residents_resident_id");

                    b.HasOne("INTEX_II.Models.Safehouse", "Safehouse")
                        .WithMany("IncidentReports")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_reports_safehouses_safehouse_id");

                    b.Navigation("Resident");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("INTEX_II.Models.InterventionPlan", b =>
                {
                    b.HasOne("INTEX_II.Models.Resident", "Resident")
                        .WithMany("InterventionPlans")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_plans_residents_resident_id");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("INTEX_II.Models.PartnerAssignment", b =>
                {
                    b.HasOne("INTEX_II.Models.Partner", "Partner")
                        .WithMany("Assignments")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partner_assignments_partners_partner_id");

                    b.HasOne("INTEX_II.Models.Safehouse", "Safehouse")
                        .WithMany("PartnerAssignments")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_partner_assignments_safehouses_safehouse_id");

                    b.Navigation("Partner");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("INTEX_II.Models.ProcessRecording", b =>
                {
                    b.HasOne("INTEX_II.Models.Resident", "Resident")
                        .WithMany("ProcessRecordings")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_recordings_residents_resident_id");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("INTEX_II.Models.Resident", b =>
                {
                    b.HasOne("INTEX_II.Models.Safehouse", "Safehouse")
                        .WithMany("Residents")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_residents_safehouses_safehouse_id");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("INTEX_II.Models.SafehouseMonthlyMetric", b =>
                {
                    b.HasOne("INTEX_II.Models.Safehouse", "Safehouse")
                        .WithMany("MonthlyMetrics")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_safehouse_monthly_metrics_safehouses_safehouse_id");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("INTEX_II.Models.Donation", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("InKindItems");
                });

            modelBuilder.Entity("INTEX_II.Models.Partner", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("INTEX_II.Models.Resident", b =>
                {
                    b.Navigation("EducationRecords");

                    b.Navigation("HealthRecords");

                    b.Navigation("HomeVisitations");

                    b.Navigation("IncidentReports");

                    b.Navigation("InterventionPlans");

                    b.Navigation("ProcessRecordings");
                });

            modelBuilder.Entity("INTEX_II.Models.Safehouse", b =>
                {
                    b.Navigation("DonationAllocations");

                    b.Navigation("IncidentReports");

                    b.Navigation("MonthlyMetrics");

                    b.Navigation("PartnerAssignments");

                    b.Navigation("Residents");
                });

            modelBuilder.Entity("INTEX_II.Models.SocialMediaPost", b =>
                {
                    b.Navigation("ReferralDonations");
                });

            modelBuilder.Entity("INTEX_II.Models.Supporter", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
