/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#004f4f',
        'surface-container-highest': '#e1e3e4',
        'on-tertiary-fixed-variant': '#604100',
        secondary: '#006a6a',
        'on-secondary': '#ffffff',
        'secondary-container': '#90efef',
        'on-tertiary-fixed': '#281900',
        'tertiary-fixed-dim': '#ffba38',
        'surface-container-low': '#f3f4f5',
        'inverse-surface': '#2e3132',
        surface: '#f8f9fa',
        'primary-fixed': '#d7e2ff',
        'surface-dim': '#d9dadb',
        'outline-variant': '#c2c6d4',
        'on-secondary-container': '#006e6e',
        'surface-variant': '#e1e3e4',
        'on-secondary-fixed': '#002020',
        background: '#f8f9fa',
        'tertiary-fixed': '#ffdeac',
        'on-primary-fixed': '#001a40',
        'surface-bright': '#f8f9fa',
        'surface-container': '#edeeef',
        'on-surface': '#191c1d',
        'tertiary-container': '#775200',
        outline: '#727784',
        'surface-container-high': '#e7e8e9',
        'inverse-on-surface': '#f0f1f2',
        'primary-fixed-dim': '#acc7ff',
        'on-primary-fixed-variant': '#004491',
        'primary-container': '#0056b3',
        primary: '#003f87',
        'surface-tint': '#115cb9',
        'on-background': '#191c1d',
        'secondary-fixed': '#93f2f2',
        'secondary-fixed-dim': '#76d6d5',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        tertiary: '#593c00',
        'on-primary-container': '#bbd0ff',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#acc7ff',
        'on-tertiary-container': '#ffc769',
        'on-error': '#ffffff',
        'on-surface-variant': '#424752',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
