-- ============================================================
-- Location & Date Updates: Philippines → Central America
-- + Resident admission year redistribution (YoY trend fix)
-- ============================================================
BEGIN;

-- ------------------------------------------------------------
-- 1. Safehouses: update region, city, province, country
-- ------------------------------------------------------------
UPDATE safehouses SET region = 'Caribbean Coast', city = 'Quetzaltenango', province = 'Guatemala Dept.', country = 'Guatemala' WHERE safehouse_id = 1;
UPDATE safehouses SET region = 'Central Region', city = 'El Progreso', province = 'Yoro', country = 'Honduras' WHERE safehouse_id = 2;
UPDATE safehouses SET region = 'Caribbean Coast', city = 'Santa Ana', province = 'Santa Ana', country = 'El Salvador' WHERE safehouse_id = 3;
UPDATE safehouses SET region = 'Western Region', city = 'Bluefields', province = 'León', country = 'Nicaragua' WHERE safehouse_id = 4;
UPDATE safehouses SET region = 'Northern Region', city = 'Heredia', province = 'San José Province', country = 'Costa Rica' WHERE safehouse_id = 5;
UPDATE safehouses SET region = 'Central Region', city = 'San Miguelito', province = 'Colón Province', country = 'Panama' WHERE safehouse_id = 6;
UPDATE safehouses SET region = 'Northern Region', city = 'Santa Rosa', province = 'Copan', country = 'Honduras' WHERE safehouse_id = 7;
UPDATE safehouses SET region = 'Caribbean Coast', city = 'Siguatepeque', province = 'Yoro', country = 'Honduras' WHERE safehouse_id = 8;
UPDATE safehouses SET region = 'Central Region', city = 'Ilopango', province = 'Ahuachapán', country = 'El Salvador' WHERE safehouse_id = 9;

-- ------------------------------------------------------------
-- 2. Residents: update place_of_birth and date_of_admission
-- ------------------------------------------------------------
UPDATE residents SET place_of_birth = 'Ilopango', date_of_admission = '2025-04-24' WHERE resident_id = 1;
UPDATE residents SET place_of_birth = 'Juigalpa', date_of_admission = '2025-11-18' WHERE resident_id = 2;
UPDATE residents SET place_of_birth = 'Danlí', date_of_admission = '2024-05-24' WHERE resident_id = 3;
UPDATE residents SET place_of_birth = 'San Miguelito', date_of_admission = '2025-08-03' WHERE resident_id = 4;
UPDATE residents SET place_of_birth = 'Santiago', date_of_admission = '2025-01-24' WHERE resident_id = 5;
UPDATE residents SET place_of_birth = 'Guatemala City', date_of_admission = '2025-10-26' WHERE resident_id = 6;
UPDATE residents SET place_of_birth = 'Liberia', date_of_admission = '2024-06-22' WHERE resident_id = 7;
UPDATE residents SET place_of_birth = 'San Miguelito', date_of_admission = '2024-02-28' WHERE resident_id = 8;
UPDATE residents SET place_of_birth = 'Tegucigalpa', date_of_admission = '2025-04-06' WHERE resident_id = 9;
UPDATE residents SET place_of_birth = 'Pérez Zeledón', date_of_admission = '2025-10-23' WHERE resident_id = 10;
UPDATE residents SET place_of_birth = 'Delgado', date_of_admission = '2025-03-05' WHERE resident_id = 11;
UPDATE residents SET place_of_birth = 'Soyapango', date_of_admission = '2024-06-03' WHERE resident_id = 12;
UPDATE residents SET place_of_birth = 'Danlí', date_of_admission = '2023-02-23' WHERE resident_id = 13;
UPDATE residents SET place_of_birth = 'Chimaltenango', date_of_admission = '2025-01-26' WHERE resident_id = 14;
UPDATE residents SET place_of_birth = 'La Ceiba', date_of_admission = '2024-10-18' WHERE resident_id = 15;
UPDATE residents SET place_of_birth = 'Liberia', date_of_admission = '2025-01-26' WHERE resident_id = 16;
UPDATE residents SET place_of_birth = 'Soyapango', date_of_admission = '2025-01-20' WHERE resident_id = 17;
UPDATE residents SET place_of_birth = 'Cobán', date_of_admission = '2023-12-14' WHERE resident_id = 18;
UPDATE residents SET place_of_birth = 'Huehuetenango', date_of_admission = '2025-03-10' WHERE resident_id = 19;
UPDATE residents SET place_of_birth = 'Mejicanos', date_of_admission = '2025-03-23' WHERE resident_id = 20;
UPDATE residents SET place_of_birth = 'Cobán', date_of_admission = '2023-10-09' WHERE resident_id = 21;
UPDATE residents SET place_of_birth = 'Santa Ana', date_of_admission = '2023-05-14' WHERE resident_id = 22;
UPDATE residents SET place_of_birth = 'La Chorrera', date_of_admission = '2025-10-17' WHERE resident_id = 23;
UPDATE residents SET place_of_birth = 'Santa Ana', date_of_admission = '2024-11-20' WHERE resident_id = 24;
UPDATE residents SET place_of_birth = 'Bluefields', date_of_admission = '2025-10-27' WHERE resident_id = 25;
UPDATE residents SET place_of_birth = 'Choluteca', date_of_admission = '2025-04-25' WHERE resident_id = 26;
UPDATE residents SET place_of_birth = 'San Miguelito', date_of_admission = '2025-03-17' WHERE resident_id = 27;
UPDATE residents SET place_of_birth = 'Mixco', date_of_admission = '2023-11-06' WHERE resident_id = 28;
UPDATE residents SET place_of_birth = 'Heredia', date_of_admission = '2023-03-05' WHERE resident_id = 29;
UPDATE residents SET place_of_birth = 'Usulután', date_of_admission = '2024-01-19' WHERE resident_id = 30;
UPDATE residents SET place_of_birth = 'Chinandega', date_of_admission = '2023-09-08' WHERE resident_id = 31;
UPDATE residents SET place_of_birth = 'Escuintla', date_of_admission = '2025-02-11' WHERE resident_id = 32;
UPDATE residents SET place_of_birth = 'Aguadulce', date_of_admission = '2024-12-21' WHERE resident_id = 33;
UPDATE residents SET place_of_birth = 'Mejicanos', date_of_admission = '2023-07-08' WHERE resident_id = 34;
UPDATE residents SET place_of_birth = 'Huehuetenango', date_of_admission = '2024-08-01' WHERE resident_id = 35;
UPDATE residents SET place_of_birth = 'Granada', date_of_admission = '2025-02-01' WHERE resident_id = 36;
UPDATE residents SET place_of_birth = 'Siguatepeque', date_of_admission = '2024-01-05' WHERE resident_id = 37;
UPDATE residents SET place_of_birth = 'Colón', date_of_admission = '2025-10-13' WHERE resident_id = 38;
UPDATE residents SET place_of_birth = 'San José', date_of_admission = '2024-10-10' WHERE resident_id = 39;
UPDATE residents SET place_of_birth = 'Nueva Guinea', date_of_admission = '2025-03-01' WHERE resident_id = 40;
UPDATE residents SET place_of_birth = 'Chitré', date_of_admission = '2024-04-05' WHERE resident_id = 41;
UPDATE residents SET place_of_birth = 'Santiago', date_of_admission = '2024-12-11' WHERE resident_id = 42;
UPDATE residents SET place_of_birth = 'San Miguel', date_of_admission = '2025-05-29' WHERE resident_id = 43;
UPDATE residents SET place_of_birth = 'Estelí', date_of_admission = '2023-09-13' WHERE resident_id = 44;
UPDATE residents SET place_of_birth = 'Choloma', date_of_admission = '2023-02-17' WHERE resident_id = 45;
UPDATE residents SET place_of_birth = 'Cartago', date_of_admission = '2024-01-28' WHERE resident_id = 46;
UPDATE residents SET place_of_birth = 'San Pedro Ayampuc', date_of_admission = '2025-11-19' WHERE resident_id = 47;
UPDATE residents SET place_of_birth = 'Mixco', date_of_admission = '2024-08-23' WHERE resident_id = 48;
UPDATE residents SET place_of_birth = 'Desamparados', date_of_admission = '2024-05-26' WHERE resident_id = 49;
UPDATE residents SET place_of_birth = 'El Progreso', date_of_admission = '2025-07-23' WHERE resident_id = 50;
UPDATE residents SET place_of_birth = 'Puntarenas', date_of_admission = '2024-04-14' WHERE resident_id = 51;
UPDATE residents SET place_of_birth = 'Siguatepeque', date_of_admission = '2024-02-10' WHERE resident_id = 52;
UPDATE residents SET place_of_birth = 'Huehuetenango', date_of_admission = '2023-10-09' WHERE resident_id = 53;
UPDATE residents SET place_of_birth = 'La Chorrera', date_of_admission = '2023-04-13' WHERE resident_id = 54;
UPDATE residents SET place_of_birth = 'El Progreso', date_of_admission = '2025-04-01' WHERE resident_id = 55;
UPDATE residents SET place_of_birth = 'Santiago', date_of_admission = '2024-10-16' WHERE resident_id = 56;
UPDATE residents SET place_of_birth = 'Cobán', date_of_admission = '2023-04-18' WHERE resident_id = 57;
UPDATE residents SET place_of_birth = 'Mejicanos', date_of_admission = '2025-03-14' WHERE resident_id = 58;
UPDATE residents SET place_of_birth = 'Danlí', date_of_admission = '2023-06-27' WHERE resident_id = 59;
UPDATE residents SET place_of_birth = 'Usulután', date_of_admission = '2024-01-28' WHERE resident_id = 60;

-- ------------------------------------------------------------
-- 3. Partners: update region, email, phone
-- ------------------------------------------------------------
UPDATE partners SET region = 'Northern Region', email = 'ana-reyes@yahoo.com', phone = '+507 5255 3419' WHERE partner_id = 1;
UPDATE partners SET region = 'Northern Region', email = 'maria-santos@hotmail.com', phone = '+504 6483 5030' WHERE partner_id = 2;
UPDATE partners SET region = 'Southern Region', email = 'elena-cruz@elsalvadororg.net', phone = '+503 3953 7672' WHERE partner_id = 3;
UPDATE partners SET region = 'Central Region', email = 'sofia-dizon@hondurasred.org', phone = '+504 8849 6965' WHERE partner_id = 4;
UPDATE partners SET region = 'Central Region', email = 'grace-flores@gmail.com', phone = '+504 7101 2269' WHERE partner_id = 5;
UPDATE partners SET region = 'Southern Region', email = 'joy-garcia@outlook.com', phone = '+505 9784 8018' WHERE partner_id = 6;
UPDATE partners SET region = 'Northern Region', email = 'lina-mendoza@gmail.com', phone = '+507 1462 7048' WHERE partner_id = 7;
UPDATE partners SET region = 'Central Region', email = 'noel-torres@gmail.com', phone = '+507 8932 5288' WHERE partner_id = 8;
UPDATE partners SET region = 'Northern Region', email = 'mark-lopez@gmail.com', phone = '+506 7015 4303' WHERE partner_id = 9;
UPDATE partners SET region = 'Southern Region', email = 'ramon-bautista@guatemalapartners.org', phone = '+502 7182 2782' WHERE partner_id = 10;
UPDATE partners SET region = 'Northern Region', email = 'paolo-navarro@costaricapartners.org', phone = '+506 3834 6578' WHERE partner_id = 11;
UPDATE partners SET region = 'Southern Region', email = 'jessa-ramos@hondurasred.org', phone = '+504 1509 8393' WHERE partner_id = 12;
UPDATE partners SET region = 'Central Region', email = 'mica-castillo@panamanetwork.org', phone = '+507 0310 5183' WHERE partner_id = 13;
UPDATE partners SET region = 'Southern Region', email = 'leah-gomez@nicaraguaalliance.org', phone = '+505 8299 7376' WHERE partner_id = 14;
UPDATE partners SET region = 'Northern Region', email = 'ruth-naval@guatemalapartners.org', phone = '+502 6566 7010' WHERE partner_id = 15;
UPDATE partners SET region = 'Central Region', email = 'ivan-pascual@elsalvadororg.net', phone = '+503 1333 8726' WHERE partner_id = 16;
UPDATE partners SET region = 'Northern Region', email = 'aiko-rivera@yahoo.com', phone = '+505 1781 0801' WHERE partner_id = 17;
UPDATE partners SET region = 'Northern Region', email = 'mara-salazar@outlook.com', phone = '+504 7736 0260' WHERE partner_id = 18;
UPDATE partners SET region = 'Southern Region', email = 'paula-tan@gmail.com', phone = '+505 6872 3430' WHERE partner_id = 19;
UPDATE partners SET region = 'Southern Region', email = 'chris-uy@gmail.com', phone = '+507 0097 8820' WHERE partner_id = 20;
UPDATE partners SET region = 'Northern Region', email = 'ben-diaz@gmail.com', phone = '+504 9136 1939' WHERE partner_id = 21;
UPDATE partners SET region = 'Central Region', email = 'kai-javier@nicaraguaalliance.org', phone = '+505 9985 4353' WHERE partner_id = 22;
UPDATE partners SET region = 'Central Region', email = 'tess-lim@gmail.com', phone = '+504 4751 0799' WHERE partner_id = 23;
UPDATE partners SET region = 'Northern Region', email = 'nina-vega@costaricapartners.org', phone = '+506 8425 1354' WHERE partner_id = 24;
UPDATE partners SET region = 'Southern Region', email = 'rico-ramos@costaricapartners.org', phone = '+506 4980 8412' WHERE partner_id = 25;
UPDATE partners SET region = 'Central Region', email = 'maya-serrano@outlook.com', phone = '+502 8244 9353' WHERE partner_id = 26;
UPDATE partners SET region = 'Central Region', email = 'ivy-valdez@outlook.com', phone = '+506 4016 4005' WHERE partner_id = 27;
UPDATE partners SET region = 'Central Region', email = 'paul-yap@outlook.com', phone = '+504 7868 0112' WHERE partner_id = 28;
UPDATE partners SET region = 'Northern Region', email = 'june-cortez@costaricapartners.org', phone = '+506 2620 4505' WHERE partner_id = 29;
UPDATE partners SET region = 'Southern Region', email = 'lara-soriano@yahoo.com', phone = '+504 1586 9232' WHERE partner_id = 30;

-- ------------------------------------------------------------
-- 4. Donations: update currency_code, amount, estimated_value,
--               impact_unit  (only rows originally in PHP)
-- ------------------------------------------------------------
UPDATE donations SET currency_code = 'NIO', amount = 473.34, estimated_value = 473.34, impact_unit = 'córdobas' WHERE donation_id = 1;
UPDATE donations SET currency_code = 'GTQ', amount = 150.45, estimated_value = 150.45, impact_unit = 'quetzales' WHERE donation_id = 3;
UPDATE donations SET currency_code = 'HNL', amount = 541.45, estimated_value = 541.45, impact_unit = 'lempiras' WHERE donation_id = 4;
UPDATE donations SET currency_code = 'USD', amount = 122.19, estimated_value = 122.19, impact_unit = 'dollars' WHERE donation_id = 6;
UPDATE donations SET currency_code = 'USD', amount = 108.12, estimated_value = 108.12, impact_unit = 'dollars' WHERE donation_id = 8;
UPDATE donations SET currency_code = 'NIO', amount = 1107.3, estimated_value = 1107.3, impact_unit = 'córdobas' WHERE donation_id = 10;
UPDATE donations SET currency_code = 'USD', amount = 319.17, estimated_value = 319.17, impact_unit = 'dollars' WHERE donation_id = 12;
UPDATE donations SET currency_code = 'USD', amount = 277.51, estimated_value = 277.51, impact_unit = 'dollars' WHERE donation_id = 14;
UPDATE donations SET currency_code = 'HNL', amount = 1771.81, estimated_value = 1771.81, impact_unit = 'lempiras' WHERE donation_id = 16;
UPDATE donations SET currency_code = 'USD', amount = 61.73, estimated_value = 61.73, impact_unit = 'dollars' WHERE donation_id = 19;
UPDATE donations SET currency_code = 'HNL', amount = 423.46, estimated_value = 423.46, impact_unit = 'lempiras' WHERE donation_id = 20;
UPDATE donations SET currency_code = 'USD', amount = 242.13, estimated_value = 242.13, impact_unit = 'dollars' WHERE donation_id = 21;
UPDATE donations SET currency_code = 'GTQ', amount = 155.38, estimated_value = 155.38, impact_unit = 'quetzales' WHERE donation_id = 22;
UPDATE donations SET currency_code = 'NIO', amount = 1185.67, estimated_value = 1185.67, impact_unit = 'córdobas' WHERE donation_id = 25;
UPDATE donations SET currency_code = 'GTQ', amount = 151.74, estimated_value = 151.74, impact_unit = 'quetzales' WHERE donation_id = 26;
UPDATE donations SET currency_code = 'NIO', amount = 669.34, estimated_value = 669.34, impact_unit = 'córdobas' WHERE donation_id = 29;
UPDATE donations SET currency_code = 'HNL', amount = 630.09, estimated_value = 630.09, impact_unit = 'lempiras' WHERE donation_id = 33;
UPDATE donations SET currency_code = 'HNL', amount = 412.92, estimated_value = 412.92, impact_unit = 'lempiras' WHERE donation_id = 34;
UPDATE donations SET currency_code = 'NIO', amount = 545.34, estimated_value = 545.34, impact_unit = 'córdobas' WHERE donation_id = 35;
UPDATE donations SET currency_code = 'USD', amount = 137.93, estimated_value = 137.93, impact_unit = 'dollars' WHERE donation_id = 36;
UPDATE donations SET currency_code = 'USD', amount = 198.75, estimated_value = 198.75, impact_unit = 'dollars' WHERE donation_id = 37;
UPDATE donations SET currency_code = 'HNL', amount = 250.32, estimated_value = 250.32, impact_unit = 'lempiras' WHERE donation_id = 38;
UPDATE donations SET currency_code = 'HNL', amount = 889.71, estimated_value = 889.71, impact_unit = 'lempiras' WHERE donation_id = 46;
UPDATE donations SET currency_code = 'GTQ', amount = 120.07, estimated_value = 120.07, impact_unit = 'quetzales' WHERE donation_id = 47;
UPDATE donations SET currency_code = 'USD', amount = 128.03, estimated_value = 128.03, impact_unit = 'dollars' WHERE donation_id = 49;
UPDATE donations SET currency_code = 'HNL', amount = 192.02, estimated_value = 192.02, impact_unit = 'lempiras' WHERE donation_id = 50;
UPDATE donations SET currency_code = 'NIO', amount = 445.94, estimated_value = 445.94, impact_unit = 'córdobas' WHERE donation_id = 54;
UPDATE donations SET currency_code = 'USD', amount = 255.75, estimated_value = 255.75, impact_unit = 'dollars' WHERE donation_id = 56;
UPDATE donations SET currency_code = 'USD', amount = 220.77, estimated_value = 220.77, impact_unit = 'dollars' WHERE donation_id = 57;
UPDATE donations SET currency_code = 'GTQ', amount = 160.88, estimated_value = 160.88, impact_unit = 'quetzales' WHERE donation_id = 58;
UPDATE donations SET currency_code = 'USD', amount = 250.58, estimated_value = 250.58, impact_unit = 'dollars' WHERE donation_id = 62;
UPDATE donations SET currency_code = 'USD', amount = 164.69, estimated_value = 164.69, impact_unit = 'dollars' WHERE donation_id = 63;
UPDATE donations SET currency_code = 'USD', amount = 160.71, estimated_value = 160.71, impact_unit = 'dollars' WHERE donation_id = 64;
UPDATE donations SET currency_code = 'CRC', amount = 15100.22, estimated_value = 15100.22, impact_unit = 'colones' WHERE donation_id = 66;
UPDATE donations SET currency_code = 'NIO', amount = 261.57, estimated_value = 261.57, impact_unit = 'córdobas' WHERE donation_id = 69;
UPDATE donations SET currency_code = 'USD', amount = 80.09, estimated_value = 80.09, impact_unit = 'dollars' WHERE donation_id = 70;
UPDATE donations SET currency_code = 'CRC', amount = 18293.66, estimated_value = 18293.66, impact_unit = 'colones' WHERE donation_id = 73;
UPDATE donations SET currency_code = 'USD', amount = 71.27, estimated_value = 71.27, impact_unit = 'dollars' WHERE donation_id = 77;
UPDATE donations SET currency_code = 'GTQ', amount = 279.68, estimated_value = 279.68, impact_unit = 'quetzales' WHERE donation_id = 80;
UPDATE donations SET currency_code = 'GTQ', amount = 41.41, estimated_value = 41.41, impact_unit = 'quetzales' WHERE donation_id = 81;
UPDATE donations SET currency_code = 'USD', amount = 45.0, estimated_value = 45.0, impact_unit = 'dollars' WHERE donation_id = 82;
UPDATE donations SET currency_code = 'HNL', amount = 215.42, estimated_value = 215.42, impact_unit = 'lempiras' WHERE donation_id = 83;
UPDATE donations SET currency_code = 'CRC', amount = 4905.84, estimated_value = 4905.84, impact_unit = 'colones' WHERE donation_id = 84;
UPDATE donations SET currency_code = 'USD', amount = 90.52, estimated_value = 90.52, impact_unit = 'dollars' WHERE donation_id = 85;
UPDATE donations SET currency_code = 'GTQ', amount = 302.53, estimated_value = 302.53, impact_unit = 'quetzales' WHERE donation_id = 86;
UPDATE donations SET currency_code = 'GTQ', amount = 59.33, estimated_value = 59.33, impact_unit = 'quetzales' WHERE donation_id = 87;
UPDATE donations SET currency_code = 'CRC', amount = 13591.49, estimated_value = 13591.49, impact_unit = 'colones' WHERE donation_id = 89;
UPDATE donations SET currency_code = 'NIO', amount = 310.6, estimated_value = 310.6, impact_unit = 'córdobas' WHERE donation_id = 90;
UPDATE donations SET currency_code = 'USD', amount = 83.63, estimated_value = 83.63, impact_unit = 'dollars' WHERE donation_id = 91;
UPDATE donations SET currency_code = 'USD', amount = 51.38, estimated_value = 51.38, impact_unit = 'dollars' WHERE donation_id = 92;
UPDATE donations SET currency_code = 'USD', amount = 138.17, estimated_value = 138.17, impact_unit = 'dollars' WHERE donation_id = 93;
UPDATE donations SET currency_code = 'NIO', amount = 273.12, estimated_value = 273.12, impact_unit = 'córdobas' WHERE donation_id = 94;
UPDATE donations SET currency_code = 'CRC', amount = 29664.3, estimated_value = 29664.3, impact_unit = 'colones' WHERE donation_id = 95;
UPDATE donations SET currency_code = 'CRC', amount = 22688.0, estimated_value = 22688.0, impact_unit = 'colones' WHERE donation_id = 96;
UPDATE donations SET currency_code = 'GTQ', amount = 163.41, estimated_value = 163.41, impact_unit = 'quetzales' WHERE donation_id = 99;
UPDATE donations SET currency_code = 'NIO', amount = 683.96, estimated_value = 683.96, impact_unit = 'córdobas' WHERE donation_id = 100;
UPDATE donations SET currency_code = 'CRC', amount = 2325.0, estimated_value = 2325.0, impact_unit = 'colones' WHERE donation_id = 101;
UPDATE donations SET currency_code = 'HNL', amount = 258.7, estimated_value = 258.7, impact_unit = 'lempiras' WHERE donation_id = 102;
UPDATE donations SET currency_code = 'USD', amount = 141.76, estimated_value = 141.76, impact_unit = 'dollars' WHERE donation_id = 105;
UPDATE donations SET currency_code = 'GTQ', amount = 214.86, estimated_value = 214.86, impact_unit = 'quetzales' WHERE donation_id = 106;
UPDATE donations SET currency_code = 'USD', amount = 59.36, estimated_value = 59.36, impact_unit = 'dollars' WHERE donation_id = 109;
UPDATE donations SET currency_code = 'NIO', amount = 891.22, estimated_value = 891.22, impact_unit = 'córdobas' WHERE donation_id = 110;
UPDATE donations SET currency_code = 'GTQ', amount = 139.93, estimated_value = 139.93, impact_unit = 'quetzales' WHERE donation_id = 112;
UPDATE donations SET currency_code = 'CRC', amount = 5789.34, estimated_value = 5789.34, impact_unit = 'colones' WHERE donation_id = 116;
UPDATE donations SET currency_code = 'CRC', amount = 14043.74, estimated_value = 14043.74, impact_unit = 'colones' WHERE donation_id = 119;
UPDATE donations SET currency_code = 'USD', amount = 224.02, estimated_value = 224.02, impact_unit = 'dollars' WHERE donation_id = 121;
UPDATE donations SET currency_code = 'USD', amount = 185.77, estimated_value = 185.77, impact_unit = 'dollars' WHERE donation_id = 122;
UPDATE donations SET currency_code = 'USD', amount = 316.34, estimated_value = 316.34, impact_unit = 'dollars' WHERE donation_id = 123;
UPDATE donations SET currency_code = 'USD', amount = 86.43, estimated_value = 86.43, impact_unit = 'dollars' WHERE donation_id = 124;
UPDATE donations SET currency_code = 'USD', amount = 82.9, estimated_value = 82.9, impact_unit = 'dollars' WHERE donation_id = 127;
UPDATE donations SET currency_code = 'HNL', amount = 185.29, estimated_value = 185.29, impact_unit = 'lempiras' WHERE donation_id = 129;
UPDATE donations SET currency_code = 'USD', amount = 174.9, estimated_value = 174.9, impact_unit = 'dollars' WHERE donation_id = 130;
UPDATE donations SET currency_code = 'NIO', amount = 789.29, estimated_value = 789.29, impact_unit = 'córdobas' WHERE donation_id = 131;
UPDATE donations SET currency_code = 'GTQ', amount = 70.68, estimated_value = 70.68, impact_unit = 'quetzales' WHERE donation_id = 133;
UPDATE donations SET currency_code = 'USD', amount = 125.12, estimated_value = 125.12, impact_unit = 'dollars' WHERE donation_id = 136;
UPDATE donations SET currency_code = 'USD', amount = 237.85, estimated_value = 237.85, impact_unit = 'dollars' WHERE donation_id = 139;
UPDATE donations SET currency_code = 'CRC', amount = 2962.7, estimated_value = 2962.7, impact_unit = 'colones' WHERE donation_id = 141;
UPDATE donations SET currency_code = 'USD', amount = 192.83, estimated_value = 192.83, impact_unit = 'dollars' WHERE donation_id = 142;
UPDATE donations SET currency_code = 'USD', amount = 65.67, estimated_value = 65.67, impact_unit = 'dollars' WHERE donation_id = 144;
UPDATE donations SET currency_code = 'GTQ', amount = 108.45, estimated_value = 108.45, impact_unit = 'quetzales' WHERE donation_id = 145;
UPDATE donations SET currency_code = 'USD', amount = 307.38, estimated_value = 307.38, impact_unit = 'dollars' WHERE donation_id = 150;
UPDATE donations SET currency_code = 'USD', amount = 78.65, estimated_value = 78.65, impact_unit = 'dollars' WHERE donation_id = 151;
UPDATE donations SET currency_code = 'CRC', amount = 2325.0, estimated_value = 2325.0, impact_unit = 'colones' WHERE donation_id = 152;
UPDATE donations SET currency_code = 'USD', amount = 184.33, estimated_value = 184.33, impact_unit = 'dollars' WHERE donation_id = 156;
UPDATE donations SET currency_code = 'USD', amount = 58.51, estimated_value = 58.51, impact_unit = 'dollars' WHERE donation_id = 159;
UPDATE donations SET currency_code = 'NIO', amount = 596.24, estimated_value = 596.24, impact_unit = 'córdobas' WHERE donation_id = 160;
UPDATE donations SET currency_code = 'USD', amount = 187.62, estimated_value = 187.62, impact_unit = 'dollars' WHERE donation_id = 161;
UPDATE donations SET currency_code = 'NIO', amount = 468.77, estimated_value = 468.77, impact_unit = 'córdobas' WHERE donation_id = 163;
UPDATE donations SET currency_code = 'USD', amount = 174.93, estimated_value = 174.93, impact_unit = 'dollars' WHERE donation_id = 164;
UPDATE donations SET currency_code = 'USD', amount = 61.0, estimated_value = 61.0, impact_unit = 'dollars' WHERE donation_id = 165;
UPDATE donations SET currency_code = 'CRC', amount = 29842.77, estimated_value = 29842.77, impact_unit = 'colones' WHERE donation_id = 166;
UPDATE donations SET currency_code = 'HNL', amount = 187.02, estimated_value = 187.02, impact_unit = 'lempiras' WHERE donation_id = 167;
UPDATE donations SET currency_code = 'HNL', amount = 157.09, estimated_value = 157.09, impact_unit = 'lempiras' WHERE donation_id = 169;
UPDATE donations SET currency_code = 'NIO', amount = 310.18, estimated_value = 310.18, impact_unit = 'córdobas' WHERE donation_id = 171;
UPDATE donations SET currency_code = 'USD', amount = 282.52, estimated_value = 282.52, impact_unit = 'dollars' WHERE donation_id = 173;
UPDATE donations SET currency_code = 'NIO', amount = 1032.47, estimated_value = 1032.47, impact_unit = 'córdobas' WHERE donation_id = 174;
UPDATE donations SET currency_code = 'USD', amount = 311.84, estimated_value = 311.84, impact_unit = 'dollars' WHERE donation_id = 177;
UPDATE donations SET currency_code = 'USD', amount = 407.11, estimated_value = 407.11, impact_unit = 'dollars' WHERE donation_id = 178;
UPDATE donations SET currency_code = 'HNL', amount = 449.58, estimated_value = 449.58, impact_unit = 'lempiras' WHERE donation_id = 179;
UPDATE donations SET currency_code = 'CRC', amount = 10951.68, estimated_value = 10951.68, impact_unit = 'colones' WHERE donation_id = 180;
UPDATE donations SET currency_code = 'CRC', amount = 2325.0, estimated_value = 2325.0, impact_unit = 'colones' WHERE donation_id = 182;
UPDATE donations SET currency_code = 'USD', amount = 114.95, estimated_value = 114.95, impact_unit = 'dollars' WHERE donation_id = 183;
UPDATE donations SET currency_code = 'NIO', amount = 407.29, estimated_value = 407.29, impact_unit = 'córdobas' WHERE donation_id = 184;
UPDATE donations SET currency_code = 'CRC', amount = 60278.32, estimated_value = 60278.32, impact_unit = 'colones' WHERE donation_id = 185;
UPDATE donations SET currency_code = 'GTQ', amount = 148.66, estimated_value = 148.66, impact_unit = 'quetzales' WHERE donation_id = 188;
UPDATE donations SET currency_code = 'USD', amount = 220.18, estimated_value = 220.18, impact_unit = 'dollars' WHERE donation_id = 189;
UPDATE donations SET currency_code = 'USD', amount = 186.99, estimated_value = 186.99, impact_unit = 'dollars' WHERE donation_id = 190;
UPDATE donations SET currency_code = 'HNL', amount = 231.14, estimated_value = 231.14, impact_unit = 'lempiras' WHERE donation_id = 192;
UPDATE donations SET currency_code = 'NIO', amount = 485.56, estimated_value = 485.56, impact_unit = 'córdobas' WHERE donation_id = 196;
UPDATE donations SET currency_code = 'CRC', amount = 7563.41, estimated_value = 7563.41, impact_unit = 'colones' WHERE donation_id = 198;
UPDATE donations SET currency_code = 'CRC', amount = 6429.56, estimated_value = 6429.56, impact_unit = 'colones' WHERE donation_id = 201;
UPDATE donations SET currency_code = 'USD', amount = 207.98, estimated_value = 207.98, impact_unit = 'dollars' WHERE donation_id = 202;
UPDATE donations SET currency_code = 'USD', amount = 45.0, estimated_value = 45.0, impact_unit = 'dollars' WHERE donation_id = 203;
UPDATE donations SET currency_code = 'NIO', amount = 882.47, estimated_value = 882.47, impact_unit = 'córdobas' WHERE donation_id = 205;
UPDATE donations SET currency_code = 'NIO', amount = 535.94, estimated_value = 535.94, impact_unit = 'córdobas' WHERE donation_id = 206;
UPDATE donations SET currency_code = 'NIO', amount = 765.95, estimated_value = 765.95, impact_unit = 'córdobas' WHERE donation_id = 208;
UPDATE donations SET currency_code = 'USD', amount = 251.24, estimated_value = 251.24, impact_unit = 'dollars' WHERE donation_id = 212;
UPDATE donations SET currency_code = 'HNL', amount = 278.52, estimated_value = 278.52, impact_unit = 'lempiras' WHERE donation_id = 216;
UPDATE donations SET currency_code = 'CRC', amount = 10969.07, estimated_value = 10969.07, impact_unit = 'colones' WHERE donation_id = 217;
UPDATE donations SET currency_code = 'NIO', amount = 248.8, estimated_value = 248.8, impact_unit = 'córdobas' WHERE donation_id = 218;
UPDATE donations SET currency_code = 'USD', amount = 73.7, estimated_value = 73.7, impact_unit = 'dollars' WHERE donation_id = 219;
UPDATE donations SET currency_code = 'HNL', amount = 367.86, estimated_value = 367.86, impact_unit = 'lempiras' WHERE donation_id = 220;
UPDATE donations SET currency_code = 'USD', amount = 106.9, estimated_value = 106.9, impact_unit = 'dollars' WHERE donation_id = 224;
UPDATE donations SET currency_code = 'GTQ', amount = 91.01, estimated_value = 91.01, impact_unit = 'quetzales' WHERE donation_id = 225;
UPDATE donations SET currency_code = 'USD', amount = 189.69, estimated_value = 189.69, impact_unit = 'dollars' WHERE donation_id = 227;
UPDATE donations SET currency_code = 'CRC', amount = 6708.37, estimated_value = 6708.37, impact_unit = 'colones' WHERE donation_id = 228;
UPDATE donations SET currency_code = 'USD', amount = 210.74, estimated_value = 210.74, impact_unit = 'dollars' WHERE donation_id = 229;
UPDATE donations SET currency_code = 'USD', amount = 386.77, estimated_value = 386.77, impact_unit = 'dollars' WHERE donation_id = 230;
UPDATE donations SET currency_code = 'CRC', amount = 19565.71, estimated_value = 19565.71, impact_unit = 'colones' WHERE donation_id = 231;
UPDATE donations SET currency_code = 'USD', amount = 352.65, estimated_value = 352.65, impact_unit = 'dollars' WHERE donation_id = 232;
UPDATE donations SET currency_code = 'GTQ', amount = 294.66, estimated_value = 294.66, impact_unit = 'quetzales' WHERE donation_id = 234;
UPDATE donations SET currency_code = 'HNL', amount = 681.12, estimated_value = 681.12, impact_unit = 'lempiras' WHERE donation_id = 235;
UPDATE donations SET currency_code = 'USD', amount = 480.1, estimated_value = 480.1, impact_unit = 'dollars' WHERE donation_id = 237;
UPDATE donations SET currency_code = 'USD', amount = 758.44, estimated_value = 758.44, impact_unit = 'dollars' WHERE donation_id = 238;
UPDATE donations SET currency_code = 'HNL', amount = 110.0, estimated_value = 110.0, impact_unit = 'lempiras' WHERE donation_id = 239;
UPDATE donations SET currency_code = 'HNL', amount = 726.06, estimated_value = 726.06, impact_unit = 'lempiras' WHERE donation_id = 240;
UPDATE donations SET currency_code = 'HNL', amount = 184.47, estimated_value = 184.47, impact_unit = 'lempiras' WHERE donation_id = 242;
UPDATE donations SET currency_code = 'GTQ', amount = 68.54, estimated_value = 68.54, impact_unit = 'quetzales' WHERE donation_id = 243;
UPDATE donations SET currency_code = 'GTQ', amount = 228.71, estimated_value = 228.71, impact_unit = 'quetzales' WHERE donation_id = 245;
UPDATE donations SET currency_code = 'HNL', amount = 1076.96, estimated_value = 1076.96, impact_unit = 'lempiras' WHERE donation_id = 246;
UPDATE donations SET currency_code = 'NIO', amount = 455.3, estimated_value = 455.3, impact_unit = 'córdobas' WHERE donation_id = 250;
UPDATE donations SET currency_code = 'CRC', amount = 18868.77, estimated_value = 18868.77, impact_unit = 'colones' WHERE donation_id = 251;
UPDATE donations SET currency_code = 'GTQ', amount = 117.35, estimated_value = 117.35, impact_unit = 'quetzales' WHERE donation_id = 254;
UPDATE donations SET currency_code = 'NIO', amount = 855.1, estimated_value = 855.1, impact_unit = 'córdobas' WHERE donation_id = 255;
UPDATE donations SET currency_code = 'NIO', amount = 993.26, estimated_value = 993.26, impact_unit = 'córdobas' WHERE donation_id = 256;
UPDATE donations SET currency_code = 'USD', amount = 112.85, estimated_value = 112.85, impact_unit = 'dollars' WHERE donation_id = 258;
UPDATE donations SET currency_code = 'CRC', amount = 9458.94, estimated_value = 9458.94, impact_unit = 'colones' WHERE donation_id = 260;
UPDATE donations SET currency_code = 'HNL', amount = 300.76, estimated_value = 300.76, impact_unit = 'lempiras' WHERE donation_id = 262;
UPDATE donations SET currency_code = 'USD', amount = 67.34, estimated_value = 67.34, impact_unit = 'dollars' WHERE donation_id = 266;
UPDATE donations SET currency_code = 'USD', amount = 124.93, estimated_value = 124.93, impact_unit = 'dollars' WHERE donation_id = 267;
UPDATE donations SET currency_code = 'NIO', amount = 207.34, estimated_value = 207.34, impact_unit = 'córdobas' WHERE donation_id = 269;
UPDATE donations SET currency_code = 'NIO', amount = 907.36, estimated_value = 907.36, impact_unit = 'córdobas' WHERE donation_id = 271;
UPDATE donations SET currency_code = 'NIO', amount = 281.89, estimated_value = 281.89, impact_unit = 'córdobas' WHERE donation_id = 272;
UPDATE donations SET currency_code = 'HNL', amount = 440.22, estimated_value = 440.22, impact_unit = 'lempiras' WHERE donation_id = 274;
UPDATE donations SET currency_code = 'HNL', amount = 311.1, estimated_value = 311.1, impact_unit = 'lempiras' WHERE donation_id = 276;
UPDATE donations SET currency_code = 'USD', amount = 61.85, estimated_value = 61.85, impact_unit = 'dollars' WHERE donation_id = 277;
UPDATE donations SET currency_code = 'USD', amount = 118.01, estimated_value = 118.01, impact_unit = 'dollars' WHERE donation_id = 278;
UPDATE donations SET currency_code = 'GTQ', amount = 58.12, estimated_value = 58.12, impact_unit = 'quetzales' WHERE donation_id = 279;
UPDATE donations SET currency_code = 'GTQ', amount = 81.63, estimated_value = 81.63, impact_unit = 'quetzales' WHERE donation_id = 280;
UPDATE donations SET currency_code = 'NIO', amount = 218.22, estimated_value = 218.22, impact_unit = 'córdobas' WHERE donation_id = 283;
UPDATE donations SET currency_code = 'HNL', amount = 1098.51, estimated_value = 1098.51, impact_unit = 'lempiras' WHERE donation_id = 286;
UPDATE donations SET currency_code = 'HNL', amount = 252.7, estimated_value = 252.7, impact_unit = 'lempiras' WHERE donation_id = 288;
UPDATE donations SET currency_code = 'USD', amount = 69.48, estimated_value = 69.48, impact_unit = 'dollars' WHERE donation_id = 291;
UPDATE donations SET currency_code = 'CRC', amount = 6174.64, estimated_value = 6174.64, impact_unit = 'colones' WHERE donation_id = 295;
UPDATE donations SET currency_code = 'NIO', amount = 378.58, estimated_value = 378.58, impact_unit = 'córdobas' WHERE donation_id = 296;
UPDATE donations SET currency_code = 'GTQ', amount = 44.81, estimated_value = 44.81, impact_unit = 'quetzales' WHERE donation_id = 297;
UPDATE donations SET currency_code = 'CRC', amount = 21053.81, estimated_value = 21053.81, impact_unit = 'colones' WHERE donation_id = 300;
UPDATE donations SET currency_code = 'HNL', amount = 506.59, estimated_value = 506.59, impact_unit = 'lempiras' WHERE donation_id = 302;
UPDATE donations SET currency_code = 'GTQ', amount = 245.34, estimated_value = 245.34, impact_unit = 'quetzales' WHERE donation_id = 303;
UPDATE donations SET currency_code = 'NIO', amount = 299.65, estimated_value = 299.65, impact_unit = 'córdobas' WHERE donation_id = 307;
UPDATE donations SET currency_code = 'HNL', amount = 144.8, estimated_value = 144.8, impact_unit = 'lempiras' WHERE donation_id = 311;
UPDATE donations SET currency_code = 'NIO', amount = 337.94, estimated_value = 337.94, impact_unit = 'córdobas' WHERE donation_id = 314;
UPDATE donations SET currency_code = 'USD', amount = 55.89, estimated_value = 55.89, impact_unit = 'dollars' WHERE donation_id = 318;
UPDATE donations SET currency_code = 'CRC', amount = 3657.78, estimated_value = 3657.78, impact_unit = 'colones' WHERE donation_id = 319;
UPDATE donations SET currency_code = 'CRC', amount = 6426.11, estimated_value = 6426.11, impact_unit = 'colones' WHERE donation_id = 321;
UPDATE donations SET currency_code = 'CRC', amount = 3868.8, estimated_value = 3868.8, impact_unit = 'colones' WHERE donation_id = 323;
UPDATE donations SET currency_code = 'USD', amount = 148.68, estimated_value = 148.68, impact_unit = 'dollars' WHERE donation_id = 324;
UPDATE donations SET currency_code = 'NIO', amount = 552.1, estimated_value = 552.1, impact_unit = 'córdobas' WHERE donation_id = 326;
UPDATE donations SET currency_code = 'CRC', amount = 7218.57, estimated_value = 7218.57, impact_unit = 'colones' WHERE donation_id = 328;
UPDATE donations SET currency_code = 'USD', amount = 138.66, estimated_value = 138.66, impact_unit = 'dollars' WHERE donation_id = 329;
UPDATE donations SET currency_code = 'CRC', amount = 6666.61, estimated_value = 6666.61, impact_unit = 'colones' WHERE donation_id = 330;
UPDATE donations SET currency_code = 'NIO', amount = 520.94, estimated_value = 520.94, impact_unit = 'córdobas' WHERE donation_id = 333;
UPDATE donations SET currency_code = 'CRC', amount = 8416.59, estimated_value = 8416.59, impact_unit = 'colones' WHERE donation_id = 334;
UPDATE donations SET currency_code = 'NIO', amount = 377.32, estimated_value = 377.32, impact_unit = 'córdobas' WHERE donation_id = 335;
UPDATE donations SET currency_code = 'HNL', amount = 174.19, estimated_value = 174.19, impact_unit = 'lempiras' WHERE donation_id = 336;
UPDATE donations SET currency_code = 'USD', amount = 45.0, estimated_value = 45.0, impact_unit = 'dollars' WHERE donation_id = 338;
UPDATE donations SET currency_code = 'NIO', amount = 937.83, estimated_value = 937.83, impact_unit = 'córdobas' WHERE donation_id = 341;
UPDATE donations SET currency_code = 'NIO', amount = 272.71, estimated_value = 272.71, impact_unit = 'córdobas' WHERE donation_id = 343;
UPDATE donations SET currency_code = 'USD', amount = 133.42, estimated_value = 133.42, impact_unit = 'dollars' WHERE donation_id = 344;
UPDATE donations SET currency_code = 'HNL', amount = 853.71, estimated_value = 853.71, impact_unit = 'lempiras' WHERE donation_id = 345;
UPDATE donations SET currency_code = 'USD', amount = 288.78, estimated_value = 288.78, impact_unit = 'dollars' WHERE donation_id = 346;
UPDATE donations SET currency_code = 'USD', amount = 218.85, estimated_value = 218.85, impact_unit = 'dollars' WHERE donation_id = 350;
UPDATE donations SET currency_code = 'CRC', amount = 9410.3, estimated_value = 9410.3, impact_unit = 'colones' WHERE donation_id = 351;
UPDATE donations SET currency_code = 'NIO', amount = 258.78, estimated_value = 258.78, impact_unit = 'córdobas' WHERE donation_id = 352;
UPDATE donations SET currency_code = 'USD', amount = 473.07, estimated_value = 473.07, impact_unit = 'dollars' WHERE donation_id = 353;
UPDATE donations SET currency_code = 'HNL', amount = 938.96, estimated_value = 938.96, impact_unit = 'lempiras' WHERE donation_id = 357;
UPDATE donations SET currency_code = 'USD', amount = 144.71, estimated_value = 144.71, impact_unit = 'dollars' WHERE donation_id = 358;
UPDATE donations SET currency_code = 'NIO', amount = 669.68, estimated_value = 669.68, impact_unit = 'córdobas' WHERE donation_id = 359;
UPDATE donations SET currency_code = 'GTQ', amount = 97.38, estimated_value = 97.38, impact_unit = 'quetzales' WHERE donation_id = 361;
UPDATE donations SET currency_code = 'USD', amount = 105.34, estimated_value = 105.34, impact_unit = 'dollars' WHERE donation_id = 362;
UPDATE donations SET currency_code = 'USD', amount = 326.24, estimated_value = 326.24, impact_unit = 'dollars' WHERE donation_id = 363;
UPDATE donations SET currency_code = 'HNL', amount = 335.65, estimated_value = 335.65, impact_unit = 'lempiras' WHERE donation_id = 364;
UPDATE donations SET currency_code = 'USD', amount = 164.71, estimated_value = 164.71, impact_unit = 'dollars' WHERE donation_id = 366;
UPDATE donations SET currency_code = 'USD', amount = 96.63, estimated_value = 96.63, impact_unit = 'dollars' WHERE donation_id = 368;
UPDATE donations SET currency_code = 'USD', amount = 193.79, estimated_value = 193.79, impact_unit = 'dollars' WHERE donation_id = 369;
UPDATE donations SET currency_code = 'CRC', amount = 23247.58, estimated_value = 23247.58, impact_unit = 'colones' WHERE donation_id = 370;
UPDATE donations SET currency_code = 'GTQ', amount = 323.47, estimated_value = 323.47, impact_unit = 'quetzales' WHERE donation_id = 371;
UPDATE donations SET currency_code = 'HNL', amount = 110.0, estimated_value = 110.0, impact_unit = 'lempiras' WHERE donation_id = 372;
UPDATE donations SET currency_code = 'HNL', amount = 1128.61, estimated_value = 1128.61, impact_unit = 'lempiras' WHERE donation_id = 374;
UPDATE donations SET currency_code = 'HNL', amount = 110.0, estimated_value = 110.0, impact_unit = 'lempiras' WHERE donation_id = 375;
UPDATE donations SET currency_code = 'NIO', amount = 477.89, estimated_value = 477.89, impact_unit = 'córdobas' WHERE donation_id = 376;
UPDATE donations SET currency_code = 'USD', amount = 204.59, estimated_value = 204.59, impact_unit = 'dollars' WHERE donation_id = 378;
UPDATE donations SET currency_code = 'HNL', amount = 110.0, estimated_value = 110.0, impact_unit = 'lempiras' WHERE donation_id = 379;
UPDATE donations SET currency_code = 'USD', amount = 251.93, estimated_value = 251.93, impact_unit = 'dollars' WHERE donation_id = 380;
UPDATE donations SET currency_code = 'HNL', amount = 237.01, estimated_value = 237.01, impact_unit = 'lempiras' WHERE donation_id = 381;
UPDATE donations SET currency_code = 'GTQ', amount = 104.76, estimated_value = 104.76, impact_unit = 'quetzales' WHERE donation_id = 382;
UPDATE donations SET currency_code = 'NIO', amount = 997.0, estimated_value = 997.0, impact_unit = 'córdobas' WHERE donation_id = 383;
UPDATE donations SET currency_code = 'NIO', amount = 1239.91, estimated_value = 1239.91, impact_unit = 'córdobas' WHERE donation_id = 384;
UPDATE donations SET currency_code = 'USD', amount = 97.44, estimated_value = 97.44, impact_unit = 'dollars' WHERE donation_id = 387;
UPDATE donations SET currency_code = 'CRC', amount = 3366.32, estimated_value = 3366.32, impact_unit = 'colones' WHERE donation_id = 390;
UPDATE donations SET currency_code = 'NIO', amount = 767.03, estimated_value = 767.03, impact_unit = 'córdobas' WHERE donation_id = 394;
UPDATE donations SET currency_code = 'NIO', amount = 712.13, estimated_value = 712.13, impact_unit = 'córdobas' WHERE donation_id = 395;
UPDATE donations SET currency_code = 'GTQ', amount = 39.32, estimated_value = 39.32, impact_unit = 'quetzales' WHERE donation_id = 398;
UPDATE donations SET currency_code = 'HNL', amount = 427.79, estimated_value = 427.79, impact_unit = 'lempiras' WHERE donation_id = 399;
UPDATE donations SET currency_code = 'NIO', amount = 250.31, estimated_value = 250.31, impact_unit = 'córdobas' WHERE donation_id = 400;
UPDATE donations SET currency_code = 'NIO', amount = 192.08, estimated_value = 192.08, impact_unit = 'córdobas' WHERE donation_id = 403;
UPDATE donations SET currency_code = 'CRC', amount = 7765.59, estimated_value = 7765.59, impact_unit = 'colones' WHERE donation_id = 404;
UPDATE donations SET currency_code = 'USD', amount = 45.0, estimated_value = 45.0, impact_unit = 'dollars' WHERE donation_id = 407;
UPDATE donations SET currency_code = 'GTQ', amount = 167.17, estimated_value = 167.17, impact_unit = 'quetzales' WHERE donation_id = 408;
UPDATE donations SET currency_code = 'CRC', amount = 6490.84, estimated_value = 6490.84, impact_unit = 'colones' WHERE donation_id = 409;
UPDATE donations SET currency_code = 'NIO', amount = 309.69, estimated_value = 309.69, impact_unit = 'córdobas' WHERE donation_id = 413;
UPDATE donations SET currency_code = 'NIO', amount = 739.91, estimated_value = 739.91, impact_unit = 'córdobas' WHERE donation_id = 416;
UPDATE donations SET currency_code = 'GTQ', amount = 48.95, estimated_value = 48.95, impact_unit = 'quetzales' WHERE donation_id = 417;
UPDATE donations SET currency_code = 'USD', amount = 346.42, estimated_value = 346.42, impact_unit = 'dollars' WHERE donation_id = 418;

COMMIT;
